### ISSUE TITLE
Labeled images missing

### ISSUE THREAD

**Issue by miyurusankalpa** [navinduJay/Face-Detection#3]
In main.js there is an reference of label `Logan`, which is missing in the repo folder.

**Comment by navinduJay** [comment]
working on it sir!

**Comment by navinduJay** [comment]
Issue fixed. @miyurusankalpa 
![logan](https://user-images.githubusercontent.com/37280709/96358662-4e4d0800-1127-11eb-9d46-76428e3bf8f0.PNG)
